---
- hosts: api
  become: yes
  roles:
    - role: antoiner77.caddy
      caddy_update: yes
      caddy_features: cors%2Cgit
      caddy_config: |
        ms-api.fullyforged.com

        tls tools@fullyforged.com

        cors /search {
          origin http://localhost:8000 https://ms.fullyforged.com
          max_age 0
          methods GET
        }

        proxy /search/spotify https://api.spotify.com/v1/search {
          without /search/spotify
        }

        proxy /search/apple-music https://itunes.apple.com/search {
          without /search/apple-music
        }

